In [1]:
import pandas as pd 
from bs4 import BeautifulSoup
import requests

In [17]:
url = 'https://remoteok.com/'


HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )
}

try:
    r_ = requests.get(url, headers=HEADERS, allow_redirects=False, timeout=10)
    print(r_.status_code)
except Exception as e:
    print(f"Error: {e}")

200

In [18]:
print(r_.text)

<!doctype html><html lang="en" class="   pageType-frontpage  remoteok    minimize-header   catch-emails-enabled">	<head>



					<link rel="stylesheet" href="/global.css?1780743778">
					<script>
													var userIsAdmin=false;
											</script>
					<meta charset="UTF-8">
					<title>Remote Jobs in Programming, Design, Sales and more #OpenSalaries</title>
					<meta name="description" content="Looking for a remote job? Remote OK® is the #1 Remote Job Platform and has 1,134,166+ remote jobs as a Developer, Designer, Copywriter, Customer Support Rep, Sales Professional, Project Manager and more! Find a career where you can work remotely from anywhere.">
					<meta name="msvalidate.01" content="5E0F32F90CCE5417B26666C526F8B071" />
											<meta name="viewport" content="width=device-width, initial-scale=1">


					<meta http-equiv="Content-Language" content="en-US">
					<link rel="search" type="application/opensearchdescription+xml" title="Remote OK" href="/opensearch.xml">
					<meta name="google" value="notranslate">

					<link rel='alternate' type='application/rss+xml' title='Remote Jobs in RSS' href='/remote-jobs.rss'>
					<link rel='alternate' type='application/json' title='Remote Jobs in JSON' href='/remote-jobs.json'>
					<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
					<meta name="mobile-web-app-capable" content="yes">
					<meta name="mobile-web-app-status-bar-style" content="black">
					<meta http-equiv="cleartype" content="on">
					<meta name="HandheldFriendly" content="true" >
					<meta property="og:title" content="Remote Jobs in Programming, Design, Sales and more #OpenSalaries"/>
					<meta property="og:url" content="https://remoteok.com/"/>
					<meta property="og:site_name" content="Remote OK">
					<meta property="og:description" content="Looking for a remote job? Remote OK® is the #1 Remote Job Platform and has 1,134,166+ remote jobs as a Developer, Designer, Copywriter, Customer Support Rep, Sales Professional, Project Manager and more! Find a career where you can work remotely from anywhere."/>
					<meta property="og:image" content="https://remoteok.com/assets/og-image-2021b.png"/>
					<meta property="og:type" content="website"/>
					<meta property="og:updated_time" content="2026-06-05T18:33:48+00:00"/>
					<meta http-equiv="last-modified" content="2026-06-05T18:33:48+00:00">

					<link rel="canonical" href="https://remoteok.com/" />

					<meta name="last-modified" content="2026-06-05T18:33:48+00:00">
					<meta name="twitter:card" content="summary_large_image">


					<meta name="twitter:site" content="@remoteok">
					<meta name="twitter:creator" content="@remoteok">
					<meta name="twitter:title" content="Remote Jobs in Programming, Design, Sales and more #OpenSalaries">
					<meta name="twitter:description" content="Looking for a remote job? Remote OK® is the #1 Remote Job Platform and has 1,134,166+ remote jobs as a Developer, Designer, Copywriter, Customer Support Rep, Sales Professional, Project Manager and more! Find a career where you can work remotely from anywhere.">
					<meta name="twitter:image:src" content="https://remoteok.com/assets/og-image-2021b.png">
					<meta name="twitter:url" content="http://remoteok.com/">
					<script type="application/ld+json">
						{
							"@context": "http://schema.org",
							"@type": "Organization",
							"name": "Remote OK",
							"naics": "5613",
							"url": "https://remoteok.com",
							"logo": "https://remoteok.com/assets/logo.png"
						}
					</script>
					<link rel="image_src" href="https://remoteok.com/assets/og-image-2021b.png">
											<link rel="icon" class="remoteok-favicon" href="https://remoteok.com/assets/favicon-32x32.png?1756575589" type="image/x-icon"/>
															<meta name="mobile-web-app-capable" content="yes">
					<meta name="mobile-web-app-status-bar-style" content="black">
					<meta name="google-site-verification" content="P440Rf_AlMGrr5oYx52-HGRr0EAHnX3kUHqrYz0E8kw">
					<link rel="apple-touch-icon" sizes="57x57" href="/assets/apple-icon-57x57.png?2">
					<link rel="apple-touch-icon" sizes="60x60" href="/assets/apple-icon-60x60.png?2">
					<link rel="apple-touch-icon" sizes="72x72" href="/assets/apple-icon-72x72.png?2">
					<link rel="apple-touch-icon" sizes="76x76" href="/assets/apple-icon-76x76.png?2">
					<link rel="apple-touch-icon" sizes="114x114" href="/assets/apple-icon-114x114.png?2">
					<link rel="apple-touch-icon" sizes="120x120" href="/assets/apple-icon-120x120.png?2">
					<link rel="apple-touch-icon" sizes="144x144" href="/assets/apple-icon-144x144.png?2">
					<link rel="apple-touch-icon" sizes="152x152" href="/assets/apple-icon-152x152.png?2">
					<link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-icon-180x180.png?2">

																<script type="application/ld+json" class="reviews-schema" data-type="all">
															{
									"@context": "http://schema.org",
									"@type": "Product",
									"name": "Remote OK",
																			"aggregateRating": {
											"@type": "AggregateRating",
											"bestRating":5,
											"ratingValue": 4.50,
											"reviewCount": 60259										}
																	}
														</script>









					<script src="/functions.js?1757013080"></script>
					<script src="/jquery.js?1755892213"></script>
					<link rel="stylesheet" href="/index.css?1781015342">



					<script>
						var originalUrl="\/";
						var pageType='frontpage';
												var pageTagTitle='';
						var pageRef='';
						var ref=pageRef;
					</script>


					<link rel="preconnect" href="https://sa.remoteok.com">
					<script>
						function saLoaded() {
							if(window.sa_pageview) {
								window.sa_pageview();
							}
						}
					</script>
					<script async defer data-auto-collect="false" onload="saLoaded()" src="https://sa.remoteok.com/latest.js"></script>
					<script>window.sa_event=window.sa_event||function(){var a=[].slice.call(arguments);window.sa_event.q?window.sa_event.q.push(a):window.sa_event.q=[a]};</script>



					<script>
						var allTags = (function () {
						    var allTags = null;
						    $.ajax({
						        'async': false,
						        'global': false,
						        'url': '/assets/all-tags.json?1782518401',
						        'dataType': "json",
						        'success': function (data) {
						            allTags = data;
						        }
						    });
						    return allTags;
						})();
					</script>
				<link rel='alternate' type='application/rss+xml' title='RSS' href='/remote-jobs.rss'>
		<link rel='alternate' type='application/json' title='JSON' href='/remote-jobs.json'>
	 	<meta name="twitter:widgets:csp" content="on">
	 			<script>
			var worldwide=false;var filterBenefits=[];var userId=false;var userIsPremium=0;
			var basicPrice=299;
			var priceForHighlightedExtra=49;
			var stripePublicKey='pk_live_thn9fkM3p9yV25rj8HwkXVJq';

			var suggestedFiltersHtml = '<div class="suggested-filter tooltip-set" data-tooltip="Suggested filter, tap to add" data-tag="exec">💼 Executive<img alt="Remove this filter" class="action-remove-this-filter" src="/assets/times-circle.svg"></div><div class="suggested-filter tooltip-set" data-tooltip="Suggested filter, tap to add" data-tag="customer support">🎧 Customer Support<img alt="Remove this filter" class="action-remove-this-filter" src="/assets/times-circle.svg"></div><div class="suggested-filter tooltip-set" data-tooltip="Suggested filter, tap to add" data-tag="marketing">🚥 Marketing<img alt="Remove this filter" class="action-remove-this-filter" src="/assets/times-circle.svg"></div><div class="suggested-filter tooltip-set" data-tooltip="Suggested filter, tap to add" data-tag="ops">♾️ Ops<img alt="Remove this filter" class="action-remove-this-filter" src="/assets/times-circle.svg"></div><div class="suggested-filter tooltip-set" data-tooltip="Suggested filter, tap to add" data-tag="education">👨‍🏫 Education<img alt="Remove this filter" class="action-remove-this-filter" src="/assets/times-circle.svg"></div><div class="suggested-filter tooltip-set" data-tooltip="Suggested filter, tap to add" data-tag="finance">💰 Finance<img alt="Remove this filter" class="action-remove-this-filter" src="/assets/times-circle.svg"></div><div class="suggested-filter tooltip-set" data-tooltip="Suggested filter, tap to add" data-tag="medical">🚑 Medical<img alt="Remove this filter" class="action-remove-this-filter" src="/assets/times-circle.svg"></div><div class="suggested-filter tooltip-set" data-tooltip="Suggested filter, tap to add" data-tag="engineer">🤓 Engineer<img alt="Remove this filter" class="action-remove-this-filter" src="/assets/times-circle.svg"></div>';
		</script>
		<script defer src="/showdown.js?1755892214"></script>
		<script defer src="/index.js?1775667008"></script>
		<script defer src="/qrcode.js?1755892214"></script>

	</head>

	<body class="">
										<div class="catch-emails" data-tag="">
				<div class="form">
			<p>
								Get new remote&nbsp;jobs sent to<input type="hidden" name="JOBTYPE" id="mce-JOBTYPE" value="jobs" />
			</p><span class="mobile"></span>
						<input type="text"  class="email"  placeholder="Type your email..." />
						<input type="hidden" class="source" value="">
			<input type="hidden" class="tag"  value="" style="margin-right:0">
			<div class="button action-subscribe">Subscribe</div>
						<div class="action-close-catch-emails">
				&times;
			</div>

			<script>
				$(function() {
					$('.catch-emails .email').bind('keyup',function(e) {
						if(e.which===13) {
							$('.catch-emails').hide();
							submitSubscribeForm();
						}
					});
					$('.action-subscribe').bind('click',function() {
						$('.catch-emails').hide();
						submitSubscribeForm();
					});
				});

				function submitSubscribeForm(recaptcha_token) {

					// just redirect sub form straight to sign up page
					window.location.href='/sign-up?email='+encodeURIComponent($('.form .email').val());

					/*
					console.log('submitSubscribeForm');
					$('html').addClass('loading');
					$.ajax({
						url: '/emails/subscribe',
						type:'GET',
						dataType:'json',
						data:{
							format:'json',
							spam_check_answer:spamCheckAnswer,
							FNAME:$('.catch-emails .name').val(),
							EMAIL:$('.catch-emails .email').val(),
							SOURCE:$('.catch-emails .source').val(),
							TAG:$('.catch-emails .tag').val(),
							recaptcha:recaptcha_token
						},
					}).done(function(reply) {
						$('html').removeClass('loading');
						if(reply.success) {
							if(!empty(pageTagTitle)) {
								setCookie('subscribed_to_newsletter_2020fix_'+pageTagTitle, 'true', 365,'/','.remoteok.com');
							}
							else {
								setCookie('subscribed_to_newsletter', 'true', 365,'/','.remoteok.com');
							}
							$('html').removeClass('catch-emails-enabled');
							alert(reply.message);
							// redir after subscribing to newsletter cuz user clicked [ create profile ]
							// "We'll now redirect you so you can sign up to get a remote worker profile and get even more targeted remote job matches."
							window.location.href='/sign-up?email='+encodeURIComponent($('.form .email').val())+'#worker';
						}
						else {
							$('.catch-emails').show();
							if(!empty(reply.message)) {
								alert(reply.message);
							}
							else {
								alert("Something went wrong!\n\nTweet @remoteok if this keeps happening!");
							}
						}

					});*/
				}
			</script>
		</div>
	</div>
					<script>

	function windowSize() {
		var e = window, a = 'inner';
		if (!('innerWidth' in window )) {
				a = 'client';
				e = document.documentElement || document.body;
		}
		return { width : e[ a+'Width' ] , height : e[ a+'Height' ] };
	}
	var windowWidth=windowSize().width;
	var windowHeight=windowSize().height;

	$(function() {
		$('.top-bar-dropdown-toggle').bind('click',function() {
			$('.top-left-logo').click();
		});

		$('body').on('dblclick', '.top-left-logo', function(e) {
			window.location.href='/';
		});
		$('.top-left-logo').bind('click',function(e) {
			e.stopPropagation();

			$('.search-filter-results').hide();
			$('.input-salary-filter-container').hide();
			$('.salary-filter-container').removeClass('active');
			$('.input-benefits-filter-container').hide();

			var top=$('.top-left-logo img').offset().top+$('.top-left-logo img').outerHeight()+7;
			var left=0;
			if(left<14) left=14;
			if(left>(windowSize().width-200)) left=(windowSize().width-200);
			if(top<14) top=14;
			if(top>(windowSize().height-200)) var top=(windowSize().height-200);
			$('.top-bar-dropdown').css('left',left+'px');
			$('.top-bar-dropdown').css('top',top+'px');
			$('html').toggleClass('top-bar-dropdown-expanded');
		});
		$('.filter-actions .top-bar-avatar').bind('dblclick',function(e) {
			e.stopPropagation();
			window.location.href='/';
		});

		$('.filter-actions .dropdown-toggle').bind('click',function() {
			$('.filter-actions .top-bar-avatar').click();
		});
		$('.filter-actions .top-bar-avatar').bind('click',function(e) {
			e.stopPropagation();
			$('.search-filter-results').hide();
			$('.input-salary-filter-container').hide();
			$('.salary-filter-container').removeClass('active');
			$('.input-benefits-filter-container').hide();

			$('.top-bar-dropdown').css('position','absolute');
			$('.top-bar-dropdown').css('left',$(this).offset().left);
			$('.top-bar-dropdown').css('top',$(this).offset().top+$(this).height()+7);
			$('html').toggleClass('top-bar-dropdown-expanded');
		});
	});
</script>


<div class="top-bar-dropdown">


			<a href="/sign-up">
			👩‍💻&nbsp;Join Remote OK
		</ap>
		<a href="/login">
			👋 &nbsp;Log in
		</a>
		<div class="top-bar-dropdown-divider">
			<div class="top-bar-dropdown-divider-label">
				General
			</div>
		</div>




	<a title="Remote OK" alt="Remote OK" href="/">
		<i><img alt="Remote OK" width="13" height="13" src="https://remoteok.com/assets/logo-square.png" style="width:13px;vertical-align:middle;border-radius:100%" /></i> Frontpage
	</a>




	<a title="Remote Jobs" alt="Remote Jobs" href="/remote-jobs">
		<i>🏝</i> Remote jobs
	</a>

			<a class="nav-item" href="/sign-up">
			🌗&nbsp; Dark mode
		</a>

	<a href="/workers">
		<i>👩‍💻</i> Hire remote workers
	</a>

	<a href="/hire-remotely?discount_code=2d66c7258635bd67926b08171dc2d067&ref=nav">
		<i>🚨</i> Post a job	</a>

			<a class="nav-item" href="/sign-up">
			<i>⭐️</i> Go premium
		</a>


	<script>
		$(function() {
			$('.action-toggle-dark-mode').bind('click',function() {
				$('html').toggleClass('dark');
				if($('html').hasClass('dark')) {
					setCookie('dark_mode','on', 365);
					setCookie('dark_mode_js_test','on', 365);
				}
				else {
					setCookie('dark_mode','off', 365);
					setCookie('dark_mode_js_test','off', 365);
				}
			});
		});
	</script>




	<div class="top-bar-dropdown-divider">
		<div class="top-bar-dropdown-divider-label">
			Top jobs
		</div>
	</div>


	<div class="a">
		<i>🦾&nbsp;</i> <a rel="noopener follow" href="https://aiok.co/?ref=remoteok" title="AI Jobs">AI Jobs</a>
	</div>


	<a href="https://asyncok.com">
		<i>⏰ </i> Async jobs
	</a>
	<a href="/?benefits=distributed_team">
		<i>🌎 </i> Distributed team
	</a>



					<a title="Remote 💼 Executive jobs" href="/remote-exec-jobs">
					💼 Executive jobs
				</a>
							<a title="Remote 🎧 Customer Support jobs" href="/remote-customer-support-jobs">
					🎧 Customer Support jobs
				</a>
							<a title="Remote 🚥 Marketing jobs" href="/remote-marketing-jobs">
					🚥 Marketing jobs
				</a>
							<a title="Remote ♾️ Ops jobs" href="/remote-ops-jobs">
					♾️ Ops jobs
				</a>
							<a title="Remote 👨‍🏫 Education jobs" href="/remote-education-jobs">
					👨‍🏫 Education jobs
				</a>
							<a title="Remote 💰 Finance jobs" href="/remote-finance-jobs">
					💰 Finance jobs
				</a>
							<a title="Remote 🚑 Medical jobs" href="/remote-medical-jobs">
					🚑 Medical jobs
				</a>
							<a title="Remote 🤓 Engineer jobs" href="/remote-engineer-jobs">
					🤓 Engineer jobs
				</a>

	<div class="top-bar-dropdown-divider">
		<div class="top-bar-dropdown-divider-label">
			Companies
		</div>
	</div>


	<a href="/hire-remotely">
		<i>🚨</i> Post a remote job
	</a>
	<a href="/buy-bundle">
		<i>📦</i> Buy a job bundle
	</a>
	<a href="/ask-for-discount">
		<i>🏷</i> Ask for a discount
	</a>

	<a href="/remote-health-companies"><i><img alt="Safetywing" width="17" height="17" src="https://remoteok.com/resize-cgi/image/format=auto,fit=contain,width=34,height=34,quality=85/https://remoteok.com/assets/safetywing.png?1755892214" style="filter:invert(1);width:17px;vertical-align:middle;margin-top:4px;margin-bottom:4px;border-radius:100%" /></i> Health insurance for teams</a>

	<a href="/nomad-health-individual"><i><img alt="Safetywing" width="17" height="17" src="https://remoteok.com/resize-cgi/image/format=auto,fit=contain,width=34,height=34,quality=85/https://remoteok.com/assets/safetywing.png?1755892214" style="filter:invert(1);width:17px;vertical-align:middle;margin-top:4px;margin-bottom:4px;border-radius:100%" /></i> Health insurance for nomads</a>





	<div class="top-bar-dropdown-divider">
		<div class="top-bar-dropdown-divider-label">
			Feeds
		</div>
	</div>

	<a rel="noopener follow" href="https://www.producthunt.com/posts/remote-ok-jobs-api"><i>🛠</i> Remote Jobs API</a>
	<a href="/rss">🪚&nbsp; RSS feed</a>
	<a href="/json">🪓&nbsp; JSON feed</a>

	<a href="/hn"><p><i><img alt="Hacker News mode" width="17" height="17" src="https://news.ycombinator.com/y18.svg" style="width:17px;vertical-align:middle;margin-top:4px;margin-bottom:4px;border-radius:100%" />&nbsp;</i> Hacker News mode</p></a>
	<a href="/vscode"><p><i><img alt="Safe for work mode" width="17" height="17" src="https://remoteok.com/resize-cgi/image/format=auto,fit=contain,width=34,height=34,quality=85/https://remoteok.com/assets/vscode-favicon.png?1755892214" style="width:17px;vertical-align:middle;margin-top:4px;margin-bottom:4px;border-radius:100%" />&nbsp;</i> Safe for work mode</p></a>







	<div class="top-bar-dropdown-divider">
		<div class="top-bar-dropdown-divider-label">
			Help
		</div>
	</div>

	<a target="_blank" href="https://remoteok.featurebase.app/" class="nav-item">
		💡&nbsp; Ideas + bugs
	</a>

	<a target="_blank" href="https://wip.co/projects/remoteok" class="nav-item">
		🚀&nbsp; Changelog
	</a>

	<a target="_blank" href="https://levelsio.com/">
		🛍️&nbsp; Merch
	</a>

	<a target="_blank" href="/faq" class="nav-item">
		🛟&nbsp; FAQ & Help
	</a>






	<div class="top-bar-dropdown-divider">
		<div class="top-bar-dropdown-divider-label">
			Other projects
		</div>
	</div>



	<a href="/remote-work-statistics">
		<i>📊</i> Remote work stats <span class="badge">new</span>
	</a>

	<a href="/remote-work-statistics#companies">
		<i>👷</i> Top remote companies
	</a>

	<a href="/remote-work-statistics#salary">
		<i>💰</i> Highest paying remote jobs
	</a>

	<a href="https://buffer.com/state-of-remote-work/2022?ref=remoteok">
		<i>🧪</i> State of remote work <span class="badge">new</span>
	</a>

	<div class="a">
		<i>🌍&nbsp;</i> <a rel="noopener follow" href="https://nomadlist.com/?ref=remoteok">Become a digital nomad</a>
	</div>

	<div class="a">
		<i>🔮&nbsp;</i> <a rel="noopener follow" href="https://web3.career/?ref=remoteok" title="Web3 Jobs">Web3 Jobs</a>
	</div>

	<div class="a">
		<i>📸&nbsp;</i> <a rel="noopener follow" href="https://photoai.com/?ref=remoteok" title="Photo AI" class="nav-item">Photo AI</a>
	</div>

	<div class="a">
		<i>🏡&nbsp;</i> <a rel="noopener follow" href="https://interiorai.com/?ref=remoteok" title="Interior AI">Interior AI</a>
	</div>

	</a>


</div>












<div class="top-right-nav">


			<span class="ad advertisement sponsored" rel="sponsored">
			<a class="button remote-health" rel="sponsored" href="/nomad-health-individual">
				Health insurance
			</a>
		</span>

			<a class="button action-post-job" href="/hire-remotely?discount_code=2d66c7258635bd67926b08171dc2d067&ref=top">

In [20]:
soup = BeautifulSoup(r_.text, "html.parser")

In [41]:
# Job rows
job_rows = soup.find("tr", {"data-offset":"9"})

In [42]:
job_rows

In [48]:
!playwright install

Downloading Chrome for Testing 148.0.7778.96 (playwright chromium v1223) from https://cdn.playwright.dev/builds/cft/148.0.7778.96/mac-arm64/chrome-mac-arm64.zip

In [53]:
import asyncio
from playwright.async_api import async_playwright

async def run():

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
        )

        page = await context.new_page()

        print("Connecting to Remote OK...")
        await page.goto("https://remoteok.com/", wait_until="networkidle")
        
        cdp_session = await page.context.new_cdp_session(page)

        print("Compiling website assest into HTML")
        snapshot = await cdp_session.send('Page.captureSnapshot', {'format': 'mhtml'})

        mhtml_content = snapshot['data']

        file = "remoteok_complete.mhtml"
        with open(file, "w", encoding="utf-8") as f:
            f.write(mhtml_content)

        print(f"Success {file}")

        await context.close()
        browser.close()

# In a Jupyter notebook, execute the async function using top-level await
await run()

Connecting to Remote OK...
Compiling website assest into HTML
Success remoteok_complete.mhtml

/var/folders/md/v_wl37p57v5_mnng5bdt123m0000gn/T/ipykernel_74524/3429188771.py:32: RuntimeWarning: coroutine 'Browser.close' was never awaited
  browser.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

In [ ]:
import asyncio
from playwright.async_api import async_playwright

async def run():
    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=False)

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
        )

        page = await context.new_page()

        print("Connecting to Remote Ok...")
        await page.goto("https://remoteok.com/", wait_until="domcontentloaded")

        
        print("Scrolling to the absolute bottom of the page...")

        previous_height = await page.evaluate("document.body.scrollHeight")
        while True:
            await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")

            await page.wait_for_timeout(2000)

            new_height = await page.evaluate("document.body.scrollHeight")
            if new_height == previous_height:
                print("Reached the bottom of the page. No more jobs loading")
                break
            previous_height = new_height

        cdp_session = await page.context.new_cdp_session(page)

        print("Compiling website assets into HTML snapshot...")
        snapshot = await cdp_session.send('Page.captureSnapshot', {'format': 'mhtml'})

        mhtml_content = snapshot['data']

        file = "remoteok_complete.mhtml"
        with open(file, "w", encoding="utf-8") as f:
            f.write(mhtml_content)

        print(f"Success: {file}")

        await context.close()
        await browser.close()

await run()

In [57]:
import email
import re

path = '/Users/apple/hiring/remoteok_complete.mhtml'

with open(path, "r") as f:
    msg = email.message_from_string(f.read())


html_content = ""
for part in msg.walk():
    if part.get_content_type() == "text/html":
        html_content = part.get_payload(decode=True).decode("utf-8", errors="ignore")
        break


soup = BeautifulSoup(html_content, "html.parser")
print(f"Successfully loaded and parsed HTML document!")
print(f"Page Target Title: {soup.title.text if soup.title else 'No title found'}")

Successfully loaded and parsed HTML document!
Page Target Title: Remote Jobs in Programming, Design, Sales and more #OpenSalaries

In [60]:
job_rows = soup.find_all("tr", id=re.compile(r"^job-\d+$"))

records = []

for row in job_rows:
    job_id = row.get("data-id", "").strip()
    slug = row.get("data-slug", "").strip()
    epoch = row.get("data-epoch", "").strip()
    apply_path = row.get("data-href", "").strip()


    # Title
    title_tag = row.find(itemprop="title")
    title = title_tag.get_text(strip=True) if title_tag else None

    # Company 
    company_tag = row.find(itemprop="name")
    company = company_tag.get_text(strip=True) if company_tag else None

    # Location
    loc_tag = row.find("div", class_="location")
    location = loc_tag.get_text(strip=True) if loc_tag else None

    # Salary
    sal_tag = row.find("div", class_="salary")
    salary_raw = sal_tag.get_text(strip=True) if sal_tag else None

    # Tags
    tag_divs = row.find_all("div", class_=re.compile(r"\btag\b"))
    tags = [t.get_text(strip=True) for t in tag_divs if t.get_text(strip=True)]

    # Posted datetime
    time_tag = row.find("time")
    posted_at = time_tag.get("datetime") if time_tag else None


    records.append(
        {
            "job_id": job_id,
            "slug": slug,
            "title": title,
            "company": company,
            "location": location,
            "salary_raw": salary_raw,
            "tags": tags,
            "posted_at": posted_at,
            "epoch": int(epoch) if epoch.isdigit() else None,
            "aply_url": f"https://remoteok.com{apply_path}" if apply_path else None
        }
    )


records

[{'job_id': '1132895',
  'slug': 'remote-support-engineer-level-1132895',
  'title': 'Support Engineer',
  'company': 'Level',
  'location': '🌏 Worldwide',
  'salary_raw': '💰 $60k - $90k',
  'tags': ['Customer Support', 'Technical'],
  'posted_at': '2026-06-05T18:33:48+00:00',
  'epoch': 1780684428,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-support-engineer-level-1132895'},
 {'job_id': '1131368',
  'slug': 'remote-sales-reps-wanted-for-high-ticket-finance-sales-fse-1131368',
  'title': 'SALES REPS WANTED FOR HIGH TICKET FINANCE SALES',
  'company': 'FSE',
  'location': '🌏 Worldwide',
  'salary_raw': '💰 $60k - $200k',
  'tags': ['Sales'],
  'posted_at': '2026-06-27T00:00:09+00:00',
  'epoch': 1782518409,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-sales-reps-wanted-for-high-ticket-finance-sales-fse-1131368'},
 {'job_id': '1132435',
  'slug': 'remote-client-delivery-manager-storyteller-1132435',
  'title': 'Client Delivery Manager',
  'company': 'Storyteller',
  'location': '🇧🇷 Brazil',
  'salary_raw': '💰 $40k - $80k',
  'tags': ['Work from Home', 'AI', 'SaaS', 'Executive'],
  'posted_at': '2026-06-27T00:00:02+00:00',
  'epoch': 1782518402,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-client-delivery-manager-storyteller-1132435'},
 {'job_id': '1134014',
  'slug': 'remote-mid-senior-ai-cinematic-video-editor-everai-1134014',
  'title': 'Mid Senior AI Cinematic Video Editor',
  'company': 'EverAI',
  'location': '🌍 Africa',
  'salary_raw': '💰 $30k - $100k',
  'tags': ['Design', 'AI', 'Other', 'Art Direction'],
  'posted_at': '2026-06-24T09:04:44+00:00',
  'epoch': 1782291884,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-mid-senior-ai-cinematic-video-editor-everai-1134014'},
 {'job_id': '1133914',
  'slug': 'remote-head-of-public-understanding-nope-1133914',
  'title': 'Head of Public Understanding',
  'company': 'NOPE',
  'location': '⛩ Asia',
  'salary_raw': '💰 $100k - $150k',
  'tags': ['Marketing',
   'Communications',
   'Content Writing',
   'AI',
   'Part Time'],
  'posted_at': '2026-06-23T03:37:28+00:00',
  'epoch': 1782185848,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-head-of-public-understanding-nope-1133914'},
 {'job_id': '1134159',
  'slug': 'remote-product-growth-expert-acquisition-afirmativa-para-pessoas-de-grupos-sub-representados-neon-pagamentos-1134159',
  'title': 'Product Growth Expert Acquisition Afirmativa para Pessoas de Grupos Sub representados',
  'company': 'Neon Pagamentos',
  'location': 'Remoto',
  'salary_raw': None,
  'tags': ['Marketing', 'Python', 'C', 'Node', 'Excel'],
  'posted_at': '2026-06-27T00:00:04+00:00',
  'epoch': 1782518404,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-product-growth-expert-acquisition-afirmativa-para-pessoas-de-grupos-sub-representados-neon-pagamentos-1134159'},
 {'job_id': '1134171',
  'slug': 'remote-property-maintenance-amp-operations-coordinator-dart-1134171',
  'title': 'Property Maintenance & Operations Coordinator',
  'company': 'Dart',
  'location': '🇰🇾 Cayman Islands',
  'salary_raw': None,
  'tags': ['Sys Admin',
   'Edu',
   'Non Tech',
   'InfoSec',
   'Technical',
   'Travel',
   'C',
   'Math',
   'Analyst',
   'Embedded',
   'Customer Support',
   'Executive',
   'Microsoft',
   'Excel',
   'Sales',
   'Coordinator',
   'Marketing',
   'Ops'],
  'posted_at': '2026-06-26T20:23:35+00:00',
  'epoch': 1782505415,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-property-maintenance-amp-operations-coordinator-dart-1134171'},
 {'job_id': '1134164',
  'slug': 'remote-common-energy-office-of-energy-amp-sustainability-1134164',
  'title': 'Common Energy',
  'company': 'Office of Energy & Sustainability',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': ['Supervisor',
   'Executive',
   'Sys Admin',
   'Customer Support',
   'Marketing',
   'Controller',
   'Finance',
   'Senior',
   'Ops',
   'Stats'],
  'posted_at': '2026-06-26T20:20:01+00:00',
  'epoch': 1782505201,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-common-energy-office-of-energy-amp-sustainability-1134164'},
 {'job_id': '1134172',
  'slug': 'remote-people-operations-specialist-vulncheck-1134172',
  'title': 'People Operations Specialist',
  'company': 'VulnCheck',
  'location': '🇺🇸 United States',
  'salary_raw': None,
  'tags': ['HR',
   'InfoSec',
   'Coordinator',
   'Customer Support',
   'Marketing',
   'Executive',
   'Ops',
   'Medical',
   'Recruiter',
   'Full Time'],
  'posted_at': '2026-06-26T19:57:38+00:00',
  'epoch': 1782503858,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-people-operations-specialist-vulncheck-1134172'},
 {'job_id': '1134158',
  'slug': 'remote-frontend-developer-junior-universia-peru-1134158',
  'title': 'Frontend Developer Junior',
  'company': 'Universia Perú',
  'location': '🇵🇪 Peru',
  'salary_raw': None,
  'tags': ['Front End', 'Developer', 'Web Developer', 'JavaScript', 'Junior'],
  'posted_at': '2026-06-26T19:18:48+00:00',
  'epoch': 1782501528,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-frontend-developer-junior-universia-peru-1134158'},
 {'job_id': '1134170',
  'slug': 'remote-analyst-customer-routing-gildan-1134170',
  'title': 'Analyst Customer Routing',
  'company': 'Gildan',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': ['Sys Admin',
   'Edu',
   'Non Tech',
   'InfoSec',
   'Technical',
   'Travel',
   'C',
   'Math',
   'Analyst',
   'Embedded',
   'Customer Support',
   'Executive',
   'Microsoft',
   'Excel',
   'Sales'],
  'posted_at': '2026-06-26T18:52:19+00:00',
  'epoch': 1782499939,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-analyst-customer-routing-gildan-1134170'},
 {'job_id': '1134154',
  'slug': 'remote-customer-support-technician-helpdesk-offboardings-amp-access-pixel-machinery-1134154',
  'title': 'Customer Support Technician Helpdesk Offboardings & Access',
  'company': 'Pixel Machinery',
  'location': '🇺🇸 United States',
  'salary_raw': None,
  'tags': ['Customer Support',
   'Design',
   'Jira',
   'SaaS',
   'HR',
   'Sys Admin',
   'InfoSec',
   'Edu',
   'Consulting',
   'Technical',
   'Developer',
   'Microsoft',
   'Executive',
   'Ops',
   'Golang',
   'Medical'],
  'posted_at': '2026-06-26T15:36:59+00:00',
  'epoch': 1782488219,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-customer-support-technician-helpdesk-offboardings-amp-access-pixel-machinery-1134154'},
 {'job_id': '1134178',
  'slug': 'remote-user-researcher-ministry-of-housing-communities-and-local-government-1134178',
  'title': 'User Researcher',
  'company': 'Ministry of Housing, Communities and Local Government',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': ['Design',
   'Embedded',
   'Sys Admin',
   'InfoSec',
   'Technical',
   'Customer Support',
   'Testing',
   'Developer',
   'Scheme',
   'SEO',
   'Executive',
   'Senior',
   'Recruiter'],
  'posted_at': '2026-06-26T15:00:23+00:00',
  'epoch': 1782486023,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-user-researcher-ministry-of-housing-communities-and-local-government-1134178'},
 {'job_id': '1134162',
  'slug': 'remote-operator-genuit-group-1134162',
  'title': 'Operator',
  'company': 'Genuit Group',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': ['Supervisor', 'Executive'],
  'posted_at': '2026-06-26T14:22:04+00:00',
  'epoch': 1782483724,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-operator-genuit-group-1134162'},
 {'job_id': '1134169',
  'slug': 'remote-aeronautical-information-service-cadet-grenada-airports-authority-1134169',
  'title': 'Aeronautical Information Service Cadet',
  'company': 'Grenada Airports Authority',
  'location': '🇬🇩 Grenada',
  'salary_raw': None,
  'tags': ['Sys Admin',
   'Edu',
   'Non Tech',
   'InfoSec',
   'Technical',
   'Travel',
   'C',
   'Math'],
  'posted_at': '2026-06-26T12:41:21+00:00',
  'epoch': 1782477681,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-aeronautical-information-service-cadet-grenada-airports-authority-1134169'},
 {'job_id': '1134155',
  'slug': 'remote-collections-manager-national-service-bureau-1134155',
  'title': 'Collections Manager',
  'company': 'National Service Bureau',
  'location': '🇺🇸 United States',
  'salary_raw': None,
  'tags': ['Customer Support',
   'Design',
   'Jira',
   'SaaS',
   'HR',
   'Sys Admin',
   'InfoSec',
   'Edu',
   'Consulting',
   'Technical',
   'Developer',
   'Microsoft',
   'Executive',
   'Ops',
   'Golang',
   'Medical',
   'Marketing'],
  'posted_at': '2026-06-26T11:15:18+00:00',
  'epoch': 1782472518,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-collections-manager-national-service-bureau-1134155'},
 {'job_id': '1134152',
  'slug': 'remote-entry-level-administrative-assistant-recruit-lytics-hiring-1134152',
  'title': 'Entry Level Administrative Assistant',
  'company': 'Recruit Lytics Hiring',
  'location': 'المدينة, المدينة المدينة السعودية',
  'salary_raw': None,
  'tags': ['Virtual Assistant',
   'Edu',
   'Customer Support',
   'Marketing',
   'Video',
   'Microsoft',
   'Executive',
   'Ops',
   'Excel'],
  'posted_at': '2026-06-26T07:51:56+00:00',
  'epoch': 1782460316,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-entry-level-administrative-assistant-recruit-lytics-hiring-1134152'},
 {'job_id': '1134138',
  'slug': 'remote-administrative-assistant-entry-level-recruit-lytics-hiring-1134138',
  'title': 'Administrative Assistant Entry Level',
  'company': 'Recruit Lytics Hiring',
  'location': '🇬🇧 United Kingdom',
  'salary_raw': None,
  'tags': ['Virtual Assistant',
   'Design',
   'Executive',
   'Coordinator',
   'Customer Support',
   'Marketing',
   'Content Writing',
   'Senior',
   'Ops',
   'Excel',
   'Ads',
   'Ecommerce',
   'Shopify',
   'Full Time',
   'Edu',
   'Travel',
   'Microsoft'],
  'posted_at': '2026-06-26T07:51:44+00:00',
  'epoch': 1782460304,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-administrative-assistant-entry-level-recruit-lytics-hiring-1134138'},
 {'job_id': '1134179',
  'slug': 'remote-human-resources-assistant-recruit-lytics-hiring-1134179',
  'title': 'Human Resources Assistant',
  'company': 'Recruit Lytics Hiring',
  'location': '🇬🇧 United Kingdom',
  'salary_raw': None,
  'tags': ['Design',
   'Embedded',
   'Sys Admin',
   'InfoSec',
   'Technical',
   'Customer Support',
   'Testing',
   'Developer',
   'Scheme',
   'SEO',
   'Executive',
   'Senior',
   'Recruiter',
   'Virtual Assistant',
   'HR',
   'Edu',
   'Marketing',
   'Microsoft',
   'Ops',
   'Excel',
   'Legal'],
  'posted_at': '2026-06-26T07:51:21+00:00',
  'epoch': 1782460281,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-human-resources-assistant-recruit-lytics-hiring-1134179'},
 {'job_id': '1134157',
  'slug': 'remote-file-clerk-recruit-lytics-hiring-1134157',
  'title': 'File Clerk',
  'company': 'Recruit Lytics Hiring',
  'location': '🇭🇰 Hong Kong',
  'salary_raw': None,
  'tags': ['Jira',
   'HR',
   'Customer Support',
   'Finance',
   'Cloud',
   'Admin',
   'Executive',
   'Ops',
   'Legal'],
  'posted_at': '2026-06-26T07:47:42+00:00',
  'epoch': 1782460062,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-file-clerk-recruit-lytics-hiring-1134157'},
 {'job_id': '1134153',
  'slug': 'remote-data-entry-specialist-assistant-administrator-recruit-lytics-hiring-1134153',
  'title': 'Data Entry Specialist Assistant Administrator',
  'company': 'Recruit Lytics Hiring',
  'location': '🇭🇰 Hong Kong',
  'salary_raw': None,
  'tags': ['Virtual Assistant',
   'Edu',
   'Customer Support',
   'Marketing',
   'Video',
   'Microsoft',
   'Executive',
   'Ops',
   'Excel',
   'Data Entry',
   'Admin'],
  'posted_at': '2026-06-26T07:47:28+00:00',
  'epoch': 1782460048,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-data-entry-specialist-assistant-administrator-recruit-lytics-hiring-1134153'},
 {'job_id': '1134137',
  'slug': 'remote-virtual-executive-assistant-recruit-lytics-hiring-1134137',
  'title': 'Virtual Executive Assistant',
  'company': 'Recruit Lytics Hiring',
  'location': 'Friesland, Friesland, Nederland',
  'salary_raw': None,
  'tags': ['Virtual Assistant',
   'Design',
   'Executive',
   'Coordinator',
   'Customer Support',
   'Marketing',
   'Content Writing',
   'Senior',
   'Ops',
   'Excel',
   'Ads',
   'Ecommerce',
   'Shopify',
   'Full Time',
   'Edu',
   'Travel'],
  'posted_at': '2026-06-26T07:46:59+00:00',
  'epoch': 1782460019,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-virtual-executive-assistant-recruit-lytics-hiring-1134137'},
 {'job_id': '1134156',
  'slug': 'remote-freelance-designer-awesomehues-1134156',
  'title': 'Freelance Designer',
  'company': 'Awesomehues',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': ['Customer Support',
   'Design',
   'Jira',
   'SaaS',
   'HR',
   'Sys Admin',
   'InfoSec',
   'Edu',
   'Consulting',
   'Technical',
   'Developer',
   'Microsoft',
   'Executive',
   'Ops',
   'Golang',
   'Medical',
   'Marketing',
   'Designer',
   'Testing',
   'Finance',
   'Excel',
   'Ads'],
  'posted_at': '2026-06-26T07:37:32+00:00',
  'epoch': 1782459452,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-freelance-designer-awesomehues-1134156'},
 {'job_id': '1134151',
  'slug': 'remote-game-tester-earn-up-500-per-game-jobsinmass-com-1134151',
  'title': 'Game Tester Earn Up $500 per Game',
  'company': 'JobsInMass.com',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': ['Executive',
   'Copywriting',
   'Marketing',
   'Speech',
   'Video',
   'Content Writing',
   'Medical',
   'Social Media',
   'Part Time',
   'Game Developer',
   'Testing'],
  'posted_at': '2026-06-26T07:10:28+00:00',
  'epoch': 1782457828,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-game-tester-earn-up-500-per-game-jobsinmass-com-1134151'},
 {'job_id': '1134150',
  'slug': 'remote-social-media-manager-ae-onlinejobs-ph-1134150',
  'title': 'SOCIAL MEDIA MANAGER �',
  'company': 'OnlineJobs.PH',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': ['Executive',
   'Copywriting',
   'Marketing',
   'Speech',
   'Video',
   'Content Writing',
   'Medical',
   'Social Media',
   'Part Time'],
  'posted_at': '2026-06-26T05:55:09+00:00',
  'epoch': 1782453309,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-social-media-manager-ae-onlinejobs-ph-1134150'},
 {'job_id': '1134136',
  'slug': 'remote-marketing-assistant-onlinejobs-ph-1134136',
  'title': 'Marketing Assistant',
  'company': 'OnlineJobs.PH',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': ['Virtual Assistant',
   'Design',
   'Executive',
   'Coordinator',
   'Customer Support',
   'Marketing',
   'Content Writing',
   'Senior',
   'Ops',
   'Excel',
   'Ads',
   'Ecommerce',
   'Shopify',
   'Full Time'],
  'posted_at': '2026-06-26T05:52:48+00:00',
  'epoch': 1782453168,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-marketing-assistant-onlinejobs-ph-1134136'},
 {'job_id': '1134141',
  'slug': 'remote-i-am-looking-for-guide-mixed-media-labs-inc-1134141',
  'title': 'I am looking for guide',
  'company': 'Mixed Media Labs, Inc.',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': [],
  'posted_at': '2026-06-26T04:03:45+00:00',
  'epoch': 1782446625,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-i-am-looking-for-guide-mixed-media-labs-inc-1134141'},
 {'job_id': '1134173',
  'slug': 'remote-claims-specialist-dtla-benefits-1134173',
  'title': 'Claims Specialist',
  'company': 'DTLA Benefits',
  'location': '🇺🇸 United States',
  'salary_raw': None,
  'tags': ['HR',
   'InfoSec',
   'Coordinator',
   'Customer Support',
   'Marketing',
   'Executive',
   'Ops',
   'Medical',
   'Recruiter',
   'Full Time',
   'Sys Admin',
   'Edu',
   'Developer',
   'Finance',
   'Math',
   'Microsoft'],
  'posted_at': '2026-06-26T03:00:49+00:00',
  'epoch': 1782442849,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-claims-specialist-dtla-benefits-1134173'},
 {'job_id': '1134149',
  'slug': 'remote-view-open-positions-minds-worth-meeting-podcast-1134149',
  'title': 'View Open Positions',
  'company': 'Minds Worth Meeting Podcast',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': ['Design',
   'Wordpress',
   'Executive',
   'Designer',
   'Ads',
   'Content Writing',
   'Ops',
   'Marketing',
   'Photoshop',
   'Illustrator',
   'Ecommerce',
   'Shopify',
   'Full Time',
   'SaaS',
   'Consulting',
   'Travel',
   'Finance',
   'Edu',
   'Senior',
   'Sales',
   'Medical'],
  'posted_at': '2026-06-26T02:13:22+00:00',
  'epoch': 1782440002,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-view-open-positions-minds-worth-meeting-podcast-1134149'},
 {'job_id': '1134174',
  'slug': 'remote-genealogista-amorim-global-1134174',
  'title': 'Genealogista',
  'company': 'Amorim Global',
  'location': '🇧🇷 Brazil',
  'salary_raw': None,
  'tags': ['Excel', 'Non Tech'],
  'posted_at': '2026-06-26T00:53:09+00:00',
  'epoch': 1782435189,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-genealogista-amorim-global-1134174'},
 {'job_id': '1134128',
  'slug': 'remote-vice-president-supply-chain-ramp-talent-1134128',
  'title': 'Vice President Supply Chain',
  'company': 'Ramp Talent',
  'location': '🇺🇸 United States',
  'salary_raw': None,
  'tags': ['Customer Support',
   'Marketing',
   'Executive',
   'Microsoft',
   'Ops',
   'Excel',
   'Biotech',
   'Medical',
   'Coordinator',
   'Finance',
   'Content Writing',
   'Sales',
   'HR',
   'Edu',
   'Testing',
   'Virtual Assistant',
   'Recruiter',
   'Full Time',
   'Travel',
   'Design',
   'Speech',
   'Senior'],
  'posted_at': '2026-06-25T23:57:41+00:00',
  'epoch': 1782431861,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-vice-president-supply-chain-ramp-talent-1134128'},
 {'job_id': '1134134',
  'slug': 'remote-asistente-de-cuentas-marketing-btl-weldon-universia-argentina-1134134',
  'title': 'Asistente de Cuentas Marketing BTL Weldon',
  'company': 'Universia Argentina',
  'location': '🇦🇷 Argentina',
  'salary_raw': None,
  'tags': ['Linguistics', 'Legal', 'Non Tech', 'Marketing'],
  'posted_at': '2026-06-25T23:36:42+00:00',
  'epoch': 1782430602,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-asistente-de-cuentas-marketing-btl-weldon-universia-argentina-1134134'},
 {'job_id': '1134130',
  'slug': 'remote-water-safety-specialist-four-seasons-1134130',
  'title': 'Water Safety Specialist',
  'company': 'Four Seasons',
  'location': '🌏 Worldwide',
  'salary_raw': None,
  'tags': ['Sys Admin',
   'Edu',
   'Technical',
   'Coordinator',
   'Customer Support',
   'Marketing',
   'Executive',
   'Travel',
   'Ops',
   'Golang',
   'Medical',
   'Engineer',
   'InfoSec',
   'Video',
   'Legal'],
  'posted_at': '2026-06-25T22:54:20+00:00',
  'epoch': 1782428060,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-water-safety-specialist-four-seasons-1134130'},
 {'job_id': '1134139',
  'slug': 'remote-chief-growth-officer-berni-and-mick-ireland-1134139',
  'title': 'Chief Growth Officer',
  'company': 'Berni and Mick Ireland',
  'location': '🇬🇧 United Kingdom',
  'salary_raw': None,
  'tags': ['Virtual Assistant',
   'Design',
   'Executive',
   'Coordinator',
   'Customer Support',
   'Marketing',
   'Content Writing',
   'Senior',
   'Ops',
   'Excel',
   'Ads',
   'Ecommerce',
   'Shopify',
   'Full Time',
   'Edu',
   'Travel',
   'Microsoft',
   'Consulting',
   'Sales'],
  'posted_at': '2026-06-25T22:45:16+00:00',
  'epoch': 1782427516,
  'aply_url': 'https://remoteok.com/remote-jobs/remote-chief-growth-officer-berni-and-mick-ireland-1134139'},
 {'job_id': '1134163',
  'slug': 'remote-leakage-inspector-williams-tucker-limited-1134163',
  'title': 'Leakage Inspector',
  'company': 'Williams Tucker Limited',
  'location': '🇬🇧 United Kingdom',
  'salary_raw': None,
  'tags': ['Supervisor', 'Executive'],
  'posted_at': '2026-06-25T20:02:18+00:00',
  'epoch': 1782417738,

In [61]:
df = pd.DataFrame(records)

In [62]:
df

,job_id,slug,title,company,location,salary_raw,tags,posted_at,epoch,aply_url
0,1132895,remote-support-engineer-level-1132895,Support Engineer,Level,🌏 Worldwide,💰 $60k - $90k,"[Customer Support, Technical]",2026-06-05T18:33:48+00:00,1780684428,https://remoteok.com/remote-jobs/remote-suppor...
1,1131368,remote-sales-reps-wanted-for-high-ticket-finan...,SALES REPS WANTED FOR HIGH TICKET FINANCE SALES,FSE,🌏 Worldwide,💰 $60k - $200k,[Sales],2026-06-27T00:00:09+00:00,1782518409,https://remoteok.com/remote-jobs/remote-sales-...
2,1132435,remote-client-delivery-manager-storyteller-113...,Client Delivery Manager,Storyteller,🇧🇷 Brazil,💰 $40k - $80k,"[Work from Home, AI, SaaS, Executive]",2026-06-27T00:00:02+00:00,1782518402,https://remoteok.com/remote-jobs/remote-client...
3,1134014,remote-mid-senior-ai-cinematic-video-editor-ev...,Mid Senior AI Cinematic Video Editor,EverAI,🌍 Africa,💰 $30k - $100k,"[Design, AI, Other, Art Direction]",2026-06-24T09:04:44+00:00,1782291884,https://remoteok.com/remote-jobs/remote-mid-se...
4,1133914,remote-head-of-public-understanding-nope-1133914,Head of Public Understanding,NOPE,⛩ Asia,💰 $100k - $150k,"[Marketing, Communications, Content Writing, A...",2026-06-23T03:37:28+00:00,1782185848,https://remoteok.com/remote-jobs/remote-head-o...
5,1134159,remote-product-growth-expert-acquisition-afirm...,Product Growth Expert Acquisition Afirmativa p...,Neon Pagamentos,Remoto,NaN,"[Marketing, Python, C, Node, Excel]",2026-06-27T00:00:04+00:00,1782518404,https://remoteok.com/remote-jobs/remote-produc...
6,1134171,remote-property-maintenance-amp-operations-coo...,Property Maintenance & Operations Coordinator,Dart,🇰🇾 Cayman Islands,NaN,"[Sys Admin, Edu, Non Tech, InfoSec, Technical,...",2026-06-26T20:23:35+00:00,1782505415,https://remoteok.com/remote-jobs/remote-proper...
7,1134164,remote-common-energy-office-of-energy-amp-sust...,Common Energy,Office of Energy & Sustainability,🌏 Worldwide,NaN,"[Supervisor, Executive, Sys Admin, Customer Su...",2026-06-26T20:20:01+00:00,1782505201,https://remoteok.com/remote-jobs/remote-common...
8,1134172,remote-people-operations-specialist-vulncheck-...,People Operations Specialist,VulnCheck,🇺🇸 United States,NaN,"[HR, InfoSec, Coordinator, Customer Support, M...",2026-06-26T19:57:38+00:00,1782503858,https://remoteok.com/remote-jobs/remote-people...
9,1134158,remote-frontend-developer-junior-universia-per...,Frontend Developer Junior,Universia Perú,🇵🇪 Peru,NaN,"[Front End, Developer, Web Developer, JavaScri...",2026-06-26T19:18:48+00:00,1782501528,https://remoteok.com/remote-jobs/remote-fronte...
10,1134170,remote-analyst-customer-routing-gildan-1134170,Analyst Customer Routing,Gildan,🌏 Worldwide,NaN,"[Sys Admin, Edu, Non Tech, InfoSec, Technical,...",2026-06-26T18:52:19+00:00,1782499939,https://remoteok.com/remote-jobs/remote-analys...
11,1134154,remote-customer-support-technician-helpdesk-of...,Customer Support Technician Helpdesk Offboardi...,Pixel Machinery,🇺🇸 United States,NaN,"[Customer Support, Design, Jira, SaaS, HR, Sys...",2026-06-26T15:36:59+00:00,1782488219,https://remoteok.com/remote-jobs/remote-custom...
12,1134178,remote-user-researcher-ministry-of-housing-com...,User Researcher,"Ministry of Housing, Communities and Local Gov...",🌏 Worldwide,NaN,"[Design, Embedded, Sys Admin, InfoSec, Technic...",2026-06-26T15:00:23+00:00,1782486023,https://remoteok.com/remote-jobs/remote-user-r...
13,1134162,remote-operator-genuit-group-1134162,Operator,Genuit Group,🌏 Worldwide,NaN,"[Supervisor, Executive]",2026-06-26T14:22:04+00:00,1782483724,https://remoteok.com/remote-jobs/remote-operat...
14,1134169,remote-aeronautical-information-service-cadet-...,Aeronautical Information Service Cadet,Grenada Airports Authority,🇬🇩 Grenada,NaN,"[Sys Admin, Edu, Non Tech, InfoSec, Technical,...",2026-06-26T12:41:21+00:00,1782477681,https://remoteok.com/remote-jobs/remote-aerona...
15,1134155,remote-collections-manager-national-service-bu...,Collections Manager,National Service Bureau,🇺🇸 United States,NaN,"[Customer Support, Design, Jira, SaaS, HR, Sys...",2026-06-26T11:15:18+00:00,1782472518,https://remoteok.com/remote-jobs/remote-collec...
16,1134152,remote-entry-level-administrative-assistant-re...,Entry Level Administrative Assistant,Recruit Lytics Hiring,"المدينة, المدينة المدينة السعودية",NaN,"[Virtual Assistant, Edu, Customer Support, Mar...",2026-06-26T07:51:56+00:00,1782460316,https://remoteok.com/remote-jobs/remote-entry-...
17,1134138,remote-administrative-assistant-entry-level-re...,Administrative Assistant Entry Level,Recruit Lytics Hiring,🇬🇧 United Kingdom,NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-26T07:51:44+00:00,1782460304,https://remoteok.com/remote-jobs/remote-admini...
18,1134179,remote-human-resources-assistant-recruit-lytic...,Human Resources Assistant,Recruit Lytics Hiring,🇬🇧 United Kingdom,NaN,"[Design, Embedded, Sys Admin, InfoSec, Technic...",2026-06-26T07:51:21+00:00,1782460281,https://remoteok.com/remote-jobs/remote-human-...
19,1134157,remote-file-clerk-recruit-lytics-hiring-1134157,File Clerk,Recruit Lytics Hiring,🇭🇰 Hong Kong,NaN,"[Jira, HR, Customer Support, Finance, Cloud, A...",2026-06-26T07:47:42+00:00,1782460062,https://remoteok.com/remote-jobs/remote-file-c...
20,1134153,remote-data-entry-specialist-assistant-adminis...,Data Entry Specialist Assistant Administrator,Recruit Lytics Hiring,🇭🇰 Hong Kong,NaN,"[Virtual Assistant, Edu, Customer Support, Mar...",2026-06-26T07:47:28+00:00,1782460048,https://remoteok.com/remote-jobs/remote-data-e...
21,1134137,remote-virtual-executive-assistant-recruit-lyt...,Virtual Executive Assistant,Recruit Lytics Hiring,"Friesland, Friesland, Nederland",NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-26T07:46:59+00:00,1782460019,https://remoteok.com/remote-jobs/remote-virtua...
22,1134156,remote-freelance-designer-awesomehues-1134156,Freelance Designer,Awesomehues,🌏 Worldwide,NaN,"[Customer Support, Design, Jira, SaaS, HR, Sys...",2026-06-26T07:37:32+00:00,1782459452,https://remoteok.com/remote-jobs/remote-freela...
23,1134151,remote-game-tester-earn-up-500-per-game-jobsin...,Game Tester Earn Up $500 per Game,JobsInMass.com,🌏 Worldwide,NaN,"[Executive, Copywriting, Marketing, Speech, Vi...",2026-06-26T07:10:28+00:00,1782457828,https://remoteok.com/remote-jobs/remote-game-t...
24,1134150,remote-social-media-manager-ae-onlinejobs-ph-1...,SOCIAL MEDIA MANAGER �,OnlineJobs.PH,🌏 Worldwide,NaN,"[Executive, Copywriting, Marketing, Speech, Vi...",2026-06-26T05:55:09+00:00,1782453309,https://remoteok.com/remote-jobs/remote-social...
25,1134136,remote-marketing-assistant-onlinejobs-ph-1134136,Marketing Assistant,OnlineJobs.PH,🌏 Worldwide,NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-26T05:52:48+00:00,1782453168,https://remoteok.com/remote-jobs/remote-market...
26,1134141,remote-i-am-looking-for-guide-mixed-media-labs...,I am looking for guide,"Mixed Media Labs, Inc.",🌏 Worldwide,NaN,[],2026-06-26T04:03:45+00:00,1782446625,https://remoteok.com/remote-jobs/remote-i-am-l...
27,1134173,remote-claims-specialist-dtla-benefits-1134173,Claims Specialist,DTLA Benefits,🇺🇸 United States,NaN,"[HR, InfoSec, Coordinator, Customer Support, M...",2026-06-26T03:00:49+00:00,1782442849,https://remoteok.com/remote-jobs/remote-claims...
28,1134149,remote-view-open-positions-minds-worth-meeting...,View Open Positions,Minds Worth Meeting Podcast,🌏 Worldwide,NaN,"[Design, Wordpress, Executive, Designer, Ads, ...",2026-06-26T02:13:22+00:00,1782440002,https://remoteok.com/remote-jobs/remote-view-o...
29,1134174,remote-genealogista-amorim-global-1134174,Genealogista,Amorim Global,🇧🇷 Brazil,NaN,"[Excel, Non Tech]",2026-06-26T00:53:09+00:00,1782435189,https://remoteok.com/remote-jobs/remote-geneal...
30,1134128,remote-vice-president-supply-chain-ramp-talent...,Vice President Supply Chain,Ramp Talent,🇺🇸 United States,NaN,"[Customer Support, Marketing, Executive, Micro...",2026-06-25T23:57:41+00:00,1782431861,https://remoteok.com/remote-jobs/remote-vice-p...
31,1134134,remote-asistente-de-cuentas-marketing-btl-weld...,Asistente de Cuentas Marketing BTL Weldon,Universia Argentina,🇦🇷 Argentina,NaN,"[Linguistics, Legal, Non Tech, Marketing]",2026-06-25T23:36:42+00:00,1782430602,https://remoteok.com/remote-jobs/remote-asiste...
32,1134130,remote-water-safety-specialist-four-seasons-11...,Water Safety Specialist,Four Seasons,🌏 Worldwide,NaN,"[Sys Admin, Edu, Technical, Coordinator, Custo...",2026-06-25T22:54:20+00:00,1782428060,https://remoteok.com/remote-jobs/remote-water-...
33,1134139,remote-chief-growth-officer-berni-and-mick-ire...,Chief Growth Officer,Berni and Mick Ireland,🇬🇧 United Kingdom,NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-25T22:45:16+00:00,1782427516,https://remoteok.com/remote-jobs/remote-chief-...
34,1134163,remote-leakage-inspector-williams-tucker-limit...,Leakage Inspector,Williams Tucker Limited,🇬🇧 United Kingdom,NaN,"[Supervisor, Executive]",2026-06-25T20:02:18+00:00,1782417738,https://remoteok.com/remote-jobs/remote-leakag...
35,1134140,remote-line-inspector-job-buzzer-1134140,Line inspector,Job Buzzer,🌏 Worldwide,NaN,[],2026-06-25T20:01:32+00:00,1782417692,https://remoteok.com/remote-jobs/remote-line-i...
36,1134124,remote-clinical-trial-associate-ollin-bioscien...,Clinical Trial Associate,Ollin Biosciences,San Francisco Bay Area,NaN,"[Customer Support, Marketing, Executive, Micro...",2026-06-25T19:29:39+00:00,1782415779,https://remoteok.com/remote-jobs/remote-clinic...
37,1134115,remote-product-fashionxyz-1134115,Product,fashionxyz,🌏 Worldwide,NaN,[],2026-06-25T17:14:27+00:00,1782407667,https://remoteok.com/remote-jobs/remote-produc...
38,1134117,remote-assistant-marketing-manager-little-caes...,Assistant Marketing Manager,Little Caesars Pizza,🌏 Worldwide,NaN,"[C, Executive, Virtual Assistant, Sys Admin, S...",2026-06-25T16:37:11+00:00,1782405431,https://remoteok.com/remote-jobs/remote-assist...
39,1134108,remote-scheduling-coordinator-entry-level-no-e...,Scheduling Coordinator Entry Level No Experien...,Travel Planning Professionals,🇺🇸 United States,NaN,"[Travel, Coordinator, Customer Support, Market...",2026-06-25T14:36:32+00:00,1782398192,https://remoteok.com/remote-jobs/remote-schedu...
40,1134127,remote-scheduling-coordinator-entry-level-trav...,Scheduling Coordinator Entry Level,Travel Planning Professionals,🇺🇸 United States,NaN,"[Customer Support, Marketing, Executive, Micro...",2026-06-25T14:35:13+00:00,1782398113,https://remoteok.com/remote-jobs/remote-schedu...
41,1134109,remote-entry-level-online-scheduling-coordinat...,Entry Level Online Scheduling Coordinator,Travel Planning Professionals,🇺🇸 United States,NaN,"[Travel, Coordinator, Customer Support, Market...",2026-06-25T14:29:08+00:00,1782397748,https://remoteok.com/remote-jobs/remote-entry-...
42,1134166,remote-school-crossing-patrol-education-author...,School Crossing Patrol,Education Authority (Northern Ireland),🌏 Worldwide,NaN,"[Supervisor, Executive, Sys Admin, Customer Su...",2026-06-25T14:24:26+00:00,1782397466,https://remoteok.com/remote-jobs/remote-school...
43,1134099,remote-preparador-de-vehiculos-hatillo-enterpr...,Preparador de Vehiculos Hatillo,Enterprise,🇵🇷 Puerto Rico,NaN,"[Project Manager, Executive, Sys Admin, InfoSe...",2026-06-25T14:06:28+00:00,1782396388,https://remoteok.com/remote-jobs/remote-prepar...
44,1134145,remote-kerendia-task-force-bayer-1134145,Kerendia Task Force,Bayer,🌏 Worldwide,NaN,"[Project Manager, Executive, Product Manager, ...",2026-06-25T13:17:49+00:00,1782393469,https://remoteok.com/remote-jobs/remote-kerend...
45,1134119,remote-speculative-application-wenzel-designte...,Speculative application,Wenzel DesignTec,🌏 Worldwide,NaN,"[Sys Admin, Edu, Technical, Marketing, Finance...",2026-06-25T12:32:54+00:00,1782390774,https://remoteok.com/remote-jobs/remote-specul...
46,1134161,remote-team-leader-supervisor-clean-bees-1134161,Team leader supervisor,Clean Bees,🇬🇧 United Kingdom,NaN,"[Supervisor, Executive]",2026-06-25T12:31:57+00:00,1782390717,https://remoteok.com/remote-jobs/remote-team-l...
47,1134146,remote-hh2-biztech-1134146,hh2,Biztech,🌏 Worldwide,NaN,"[Project Manager, Executive, Product Manager, ...",2026-06-25T09:06:30+00:00,1782378390,https://remoteok.com/remote-jobs/remote-hh2-bi...
48,1134160,remote-open-position-dauphine-americashare-113...,Open Position — Dauphine,AmericaShare,🌏 Worldwide,NaN,[],2026-06-25T07:45:07+00:00,1782373507,https://remoteok.com/remote-jobs/remote-open-p...

In [68]:
# Cleaning Process

cleaned_df = df[df["title"].notna() & (df["title"] != "")].copy()


def parse_salary(s):
    if not isinstance(s, str):
        return None, None
    s = s.replace(",", "").replace("$", "").replace("💰", "").strip()
    nums = re.findall(r"(\d+(?:\.\d+)?)\s*k?", s, re.IGNORECASE)
    multipliers = [1000 if "k" in tok.lower() else 1
        for tok in re.findall(r"(\d+(?:\.\d+)?k?)", s, re.IGNORECASE)]

    values = []
    for n, m in zip(nums, multipliers):
        values.append(int(float(n) * m))

    k_flags = [bool(re.search(r"\d+k", tok, re.IGNORECASE))
                   for tok in re.findall(r"\d+\.?\d*k?", s, re.IGNORECASE)]
    values = []
    for tok in re.findall(r"\d+\.?\d*k?", s, re.IGNORECASE):
        num = float(re.search(r"[\d.]+", tok).group())
        if "k" in tok.lower():
            num *= 1000
        values.append(int(num))
    if len(values) == 0:
        return None, None
    if len(values) == 1:
        return values[0], values[0]
    return values[0], values[1]

def strip_emoji(s):
    if not isinstance(s, str):
        return s
    return re.sub(r"^[\U00010000-\U0010ffff\s]+", "", s).strip()

cleaned_df["location"] = cleaned_df["location"].apply(strip_emoji)

cleaned_df[["salary_min", "salary_max"]] = cleaned_df["salary_raw"].apply(
    lambda s: pd.Series(parse_salary(s))
)

In [69]:
cleaned_df

,job_id,slug,title,company,location,salary_raw,tags,posted_at,epoch,aply_url,salary_min,salary_max
0,1132895,remote-support-engineer-level-1132895,Support Engineer,Level,Worldwide,💰 $60k - $90k,"[Customer Support, Technical]",2026-06-05T18:33:48+00:00,1780684428,https://remoteok.com/remote-jobs/remote-suppor...,60000.0,90000.0
1,1131368,remote-sales-reps-wanted-for-high-ticket-finan...,SALES REPS WANTED FOR HIGH TICKET FINANCE SALES,FSE,Worldwide,💰 $60k - $200k,[Sales],2026-06-27T00:00:09+00:00,1782518409,https://remoteok.com/remote-jobs/remote-sales-...,60000.0,200000.0
2,1132435,remote-client-delivery-manager-storyteller-113...,Client Delivery Manager,Storyteller,Brazil,💰 $40k - $80k,"[Work from Home, AI, SaaS, Executive]",2026-06-27T00:00:02+00:00,1782518402,https://remoteok.com/remote-jobs/remote-client...,40000.0,80000.0
3,1134014,remote-mid-senior-ai-cinematic-video-editor-ev...,Mid Senior AI Cinematic Video Editor,EverAI,Africa,💰 $30k - $100k,"[Design, AI, Other, Art Direction]",2026-06-24T09:04:44+00:00,1782291884,https://remoteok.com/remote-jobs/remote-mid-se...,30000.0,100000.0
4,1133914,remote-head-of-public-understanding-nope-1133914,Head of Public Understanding,NOPE,⛩ Asia,💰 $100k - $150k,"[Marketing, Communications, Content Writing, A...",2026-06-23T03:37:28+00:00,1782185848,https://remoteok.com/remote-jobs/remote-head-o...,100000.0,150000.0
5,1134159,remote-product-growth-expert-acquisition-afirm...,Product Growth Expert Acquisition Afirmativa p...,Neon Pagamentos,Remoto,NaN,"[Marketing, Python, C, Node, Excel]",2026-06-27T00:00:04+00:00,1782518404,https://remoteok.com/remote-jobs/remote-produc...,NaN,NaN
6,1134171,remote-property-maintenance-amp-operations-coo...,Property Maintenance & Operations Coordinator,Dart,Cayman Islands,NaN,"[Sys Admin, Edu, Non Tech, InfoSec, Technical,...",2026-06-26T20:23:35+00:00,1782505415,https://remoteok.com/remote-jobs/remote-proper...,NaN,NaN
7,1134164,remote-common-energy-office-of-energy-amp-sust...,Common Energy,Office of Energy & Sustainability,Worldwide,NaN,"[Supervisor, Executive, Sys Admin, Customer Su...",2026-06-26T20:20:01+00:00,1782505201,https://remoteok.com/remote-jobs/remote-common...,NaN,NaN
8,1134172,remote-people-operations-specialist-vulncheck-...,People Operations Specialist,VulnCheck,United States,NaN,"[HR, InfoSec, Coordinator, Customer Support, M...",2026-06-26T19:57:38+00:00,1782503858,https://remoteok.com/remote-jobs/remote-people...,NaN,NaN
9,1134158,remote-frontend-developer-junior-universia-per...,Frontend Developer Junior,Universia Perú,Peru,NaN,"[Front End, Developer, Web Developer, JavaScri...",2026-06-26T19:18:48+00:00,1782501528,https://remoteok.com/remote-jobs/remote-fronte...,NaN,NaN
10,1134170,remote-analyst-customer-routing-gildan-1134170,Analyst Customer Routing,Gildan,Worldwide,NaN,"[Sys Admin, Edu, Non Tech, InfoSec, Technical,...",2026-06-26T18:52:19+00:00,1782499939,https://remoteok.com/remote-jobs/remote-analys...,NaN,NaN
11,1134154,remote-customer-support-technician-helpdesk-of...,Customer Support Technician Helpdesk Offboardi...,Pixel Machinery,United States,NaN,"[Customer Support, Design, Jira, SaaS, HR, Sys...",2026-06-26T15:36:59+00:00,1782488219,https://remoteok.com/remote-jobs/remote-custom...,NaN,NaN
12,1134178,remote-user-researcher-ministry-of-housing-com...,User Researcher,"Ministry of Housing, Communities and Local Gov...",Worldwide,NaN,"[Design, Embedded, Sys Admin, InfoSec, Technic...",2026-06-26T15:00:23+00:00,1782486023,https://remoteok.com/remote-jobs/remote-user-r...,NaN,NaN
13,1134162,remote-operator-genuit-group-1134162,Operator,Genuit Group,Worldwide,NaN,"[Supervisor, Executive]",2026-06-26T14:22:04+00:00,1782483724,https://remoteok.com/remote-jobs/remote-operat...,NaN,NaN
14,1134169,remote-aeronautical-information-service-cadet-...,Aeronautical Information Service Cadet,Grenada Airports Authority,Grenada,NaN,"[Sys Admin, Edu, Non Tech, InfoSec, Technical,...",2026-06-26T12:41:21+00:00,1782477681,https://remoteok.com/remote-jobs/remote-aerona...,NaN,NaN
15,1134155,remote-collections-manager-national-service-bu...,Collections Manager,National Service Bureau,United States,NaN,"[Customer Support, Design, Jira, SaaS, HR, Sys...",2026-06-26T11:15:18+00:00,1782472518,https://remoteok.com/remote-jobs/remote-collec...,NaN,NaN
16,1134152,remote-entry-level-administrative-assistant-re...,Entry Level Administrative Assistant,Recruit Lytics Hiring,"المدينة, المدينة المدينة السعودية",NaN,"[Virtual Assistant, Edu, Customer Support, Mar...",2026-06-26T07:51:56+00:00,1782460316,https://remoteok.com/remote-jobs/remote-entry-...,NaN,NaN
17,1134138,remote-administrative-assistant-entry-level-re...,Administrative Assistant Entry Level,Recruit Lytics Hiring,United Kingdom,NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-26T07:51:44+00:00,1782460304,https://remoteok.com/remote-jobs/remote-admini...,NaN,NaN
18,1134179,remote-human-resources-assistant-recruit-lytic...,Human Resources Assistant,Recruit Lytics Hiring,United Kingdom,NaN,"[Design, Embedded, Sys Admin, InfoSec, Technic...",2026-06-26T07:51:21+00:00,1782460281,https://remoteok.com/remote-jobs/remote-human-...,NaN,NaN
19,1134157,remote-file-clerk-recruit-lytics-hiring-1134157,File Clerk,Recruit Lytics Hiring,Hong Kong,NaN,"[Jira, HR, Customer Support, Finance, Cloud, A...",2026-06-26T07:47:42+00:00,1782460062,https://remoteok.com/remote-jobs/remote-file-c...,NaN,NaN
20,1134153,remote-data-entry-specialist-assistant-adminis...,Data Entry Specialist Assistant Administrator,Recruit Lytics Hiring,Hong Kong,NaN,"[Virtual Assistant, Edu, Customer Support, Mar...",2026-06-26T07:47:28+00:00,1782460048,https://remoteok.com/remote-jobs/remote-data-e...,NaN,NaN
21,1134137,remote-virtual-executive-assistant-recruit-lyt...,Virtual Executive Assistant,Recruit Lytics Hiring,"Friesland, Friesland, Nederland",NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-26T07:46:59+00:00,1782460019,https://remoteok.com/remote-jobs/remote-virtua...,NaN,NaN
22,1134156,remote-freelance-designer-awesomehues-1134156,Freelance Designer,Awesomehues,Worldwide,NaN,"[Customer Support, Design, Jira, SaaS, HR, Sys...",2026-06-26T07:37:32+00:00,1782459452,https://remoteok.com/remote-jobs/remote-freela...,NaN,NaN
23,1134151,remote-game-tester-earn-up-500-per-game-jobsin...,Game Tester Earn Up $500 per Game,JobsInMass.com,Worldwide,NaN,"[Executive, Copywriting, Marketing, Speech, Vi...",2026-06-26T07:10:28+00:00,1782457828,https://remoteok.com/remote-jobs/remote-game-t...,NaN,NaN
24,1134150,remote-social-media-manager-ae-onlinejobs-ph-1...,SOCIAL MEDIA MANAGER �,OnlineJobs.PH,Worldwide,NaN,"[Executive, Copywriting, Marketing, Speech, Vi...",2026-06-26T05:55:09+00:00,1782453309,https://remoteok.com/remote-jobs/remote-social...,NaN,NaN
25,1134136,remote-marketing-assistant-onlinejobs-ph-1134136,Marketing Assistant,OnlineJobs.PH,Worldwide,NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-26T05:52:48+00:00,1782453168,https://remoteok.com/remote-jobs/remote-market...,NaN,NaN
26,1134141,remote-i-am-looking-for-guide-mixed-media-labs...,I am looking for guide,"Mixed Media Labs, Inc.",Worldwide,NaN,[],2026-06-26T04:03:45+00:00,1782446625,https://remoteok.com/remote-jobs/remote-i-am-l...,NaN,NaN
27,1134173,remote-claims-specialist-dtla-benefits-1134173,Claims Specialist,DTLA Benefits,United States,NaN,"[HR, InfoSec, Coordinator, Customer Support, M...",2026-06-26T03:00:49+00:00,1782442849,https://remoteok.com/remote-jobs/remote-claims...,NaN,NaN
28,1134149,remote-view-open-positions-minds-worth-meeting...,View Open Positions,Minds Worth Meeting Podcast,Worldwide,NaN,"[Design, Wordpress, Executive, Designer, Ads, ...",2026-06-26T02:13:22+00:00,1782440002,https://remoteok.com/remote-jobs/remote-view-o...,NaN,NaN
29,1134174,remote-genealogista-amorim-global-1134174,Genealogista,Amorim Global,Brazil,NaN,"[Excel, Non Tech]",2026-06-26T00:53:09+00:00,1782435189,https://remoteok.com/remote-jobs/remote-geneal...,NaN,NaN
30,1134128,remote-vice-president-supply-chain-ramp-talent...,Vice President Supply Chain,Ramp Talent,United States,NaN,"[Customer Support, Marketing, Executive, Micro...",2026-06-25T23:57:41+00:00,1782431861,https://remoteok.com/remote-jobs/remote-vice-p...,NaN,NaN
31,1134134,remote-asistente-de-cuentas-marketing-btl-weld...,Asistente de Cuentas Marketing BTL Weldon,Universia Argentina,Argentina,NaN,"[Linguistics, Legal, Non Tech, Marketing]",2026-06-25T23:36:42+00:00,1782430602,https://remoteok.com/remote-jobs/remote-asiste...,NaN,NaN
32,1134130,remote-water-safety-specialist-four-seasons-11...,Water Safety Specialist,Four Seasons,Worldwide,NaN,"[Sys Admin, Edu, Technical, Coordinator, Custo...",2026-06-25T22:54:20+00:00,1782428060,https://remoteok.com/remote-jobs/remote-water-...,NaN,NaN
33,1134139,remote-chief-growth-officer-berni-and-mick-ire...,Chief Growth Officer,Berni and Mick Ireland,United Kingdom,NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-25T22:45:16+00:00,1782427516,https://remoteok.com/remote-jobs/remote-chief-...,NaN,NaN
34,1134163,remote-leakage-inspector-williams-tucker-limit...,Leakage Inspector,Williams Tucker Limited,United Kingdom,NaN,"[Supervisor, Executive]",2026-06-25T20:02:18+00:00,1782417738,https://remoteok.com/remote-jobs/remote-leakag...,NaN,NaN
35,1134140,remote-line-inspector-job-buzzer-1134140,Line inspector,Job Buzzer,Worldwide,NaN,[],2026-06-25T20:01:32+00:00,1782417692,https://remoteok.com/remote-jobs/remote-line-i...,NaN,NaN
36,1134124,remote-clinical-trial-associate-ollin-bioscien...,Clinical Trial Associate,Ollin Biosciences,San Francisco Bay Area,NaN,"[Customer Support, Marketing, Executive, Micro...",2026-06-25T19:29:39+00:00,1782415779,https://remoteok.com/remote-jobs/remote-clinic...,NaN,NaN
37,1134115,remote-product-fashionxyz-1134115,Product,fashionxyz,Worldwide,NaN,[],2026-06-25T17:14:27+00:00,1782407667,https://remoteok.com/remote-jobs/remote-produc...,NaN,NaN
38,1134117,remote-assistant-marketing-manager-little-caes...,Assistant Marketing Manager,Little Caesars Pizza,Worldwide,NaN,"[C, Executive, Virtual Assistant, Sys Admin, S...",2026-06-25T16:37:11+00:00,1782405431,https://remoteok.com/remote-jobs/remote-assist...,NaN,NaN
39,1134108,remote-scheduling-coordinator-entry-level-no-e...,Scheduling Coordinator Entry Level No Experien...,Travel Planning Professionals,United States,NaN,"[Travel, Coordinator, Customer Support, Market...",2026-06-25T14:36:32+00:00,1782398192,https://remoteok.com/remote-jobs/remote-schedu...,NaN,NaN
40,1134127,remote-scheduling-coordinator-entry-level-trav...,Scheduling Coordinator Entry Level,Travel Planning Professionals,United States,NaN,"[Customer Support, Marketing, Executive, Micro...",2026-06-25T14:35:13+00:00,1782398113,https://remoteok.com/remote-jobs/remote-schedu...,NaN,NaN
41,1134109,remote-entry-level-online-scheduling-coordinat...,Entry Level Online Scheduling Coordinator,Travel Planning Professionals,United States,NaN,"[Travel, Coordinator, Customer Support, Market...",2026-06-25T14:29:08+00:00,1782397748,https://remoteok.com/remote-jobs/remote-entry-...,NaN,NaN
42,1134166,remote-school-crossing-patrol-education-author...,School Crossing Patrol,Education Authority (Northern Ireland),Worldwide,NaN,"[Supervisor, Executive, Sys Admin, Customer Su...",2026-06-25T14:24:26+00:00,1782397466,https://remoteok.com/remote-jobs/remote-school...,NaN,NaN
43,1134099,remote-preparador-de-vehiculos-hatillo-enterpr...,Preparador de Vehiculos Hatillo,Enterprise,Puerto Rico,NaN,"[Project Manager, Executive, Sys Admin, InfoSe...",2026-06-25T14:06:28+00:00,1782396388,https://remoteok.com/remote-jobs/remote-prepar...,NaN,NaN
44,1134145,remote-kerendia-task-force-bayer-1134145,Kerendia Task Force,Bayer,Worldwide,NaN,"[Project Manager, Executive, Product Manager, ...",2026-06-25T13:17:49+00:00,1782393469,https://remoteok.com/remote-jobs/remote-kerend...,NaN,NaN
45,1134119,remote-speculative-application-wenzel-designte...,Speculative application,Wenzel DesignTec,Worldwide,NaN,"[Sys Admin, Edu, Technical, Marketing, Finance...",2026-06-25T12:32:54+00:00,1782390774,https://remoteok.com/remote-jobs/remote-specul...,NaN,NaN
46,1134161,remote-team-leader-supervisor-clean-bees-1134161,Team leader supervisor,Clean Bees,United Kingdom,NaN,"[Supervisor, Executive]",2026-06-25T12:31:57+00:00,1782390717,https://remoteok.com/remote-jobs/remote-team-l...,NaN,NaN
47,1134146,remote-hh2-biztech-1134146,hh2,Biztech,Worldwide,NaN,"[Project Manager, Executive, Product Manager, ...",2026-06-25T09:06:30+00:00,1782378390,https://remoteok.com/remote-jobs/remote-hh2-bi...,NaN,NaN
48,1134160,remote-open-position-dauphine-americashare-113...,Open Position — Dauphine,AmericaShare,Worldwide,NaN,[],2026-06-25T07:45:07+00:00,1782373507,https://remoteok.com/remote-jobs/remote-open-p...,NaN,NaN

In [70]:
cleaned_df

,job_id,slug,title,company,location,salary_raw,tags,posted_at,epoch,aply_url,salary_min,salary_max
0,1132895,remote-support-engineer-level-1132895,Support Engineer,Level,Worldwide,💰 $60k - $90k,"[Customer Support, Technical]",2026-06-05T18:33:48+00:00,1780684428,https://remoteok.com/remote-jobs/remote-suppor...,60000.0,90000.0
1,1131368,remote-sales-reps-wanted-for-high-ticket-finan...,SALES REPS WANTED FOR HIGH TICKET FINANCE SALES,FSE,Worldwide,💰 $60k - $200k,[Sales],2026-06-27T00:00:09+00:00,1782518409,https://remoteok.com/remote-jobs/remote-sales-...,60000.0,200000.0
2,1132435,remote-client-delivery-manager-storyteller-113...,Client Delivery Manager,Storyteller,Brazil,💰 $40k - $80k,"[Work from Home, AI, SaaS, Executive]",2026-06-27T00:00:02+00:00,1782518402,https://remoteok.com/remote-jobs/remote-client...,40000.0,80000.0
3,1134014,remote-mid-senior-ai-cinematic-video-editor-ev...,Mid Senior AI Cinematic Video Editor,EverAI,Africa,💰 $30k - $100k,"[Design, AI, Other, Art Direction]",2026-06-24T09:04:44+00:00,1782291884,https://remoteok.com/remote-jobs/remote-mid-se...,30000.0,100000.0
4,1133914,remote-head-of-public-understanding-nope-1133914,Head of Public Understanding,NOPE,⛩ Asia,💰 $100k - $150k,"[Marketing, Communications, Content Writing, A...",2026-06-23T03:37:28+00:00,1782185848,https://remoteok.com/remote-jobs/remote-head-o...,100000.0,150000.0
5,1134159,remote-product-growth-expert-acquisition-afirm...,Product Growth Expert Acquisition Afirmativa p...,Neon Pagamentos,Remoto,NaN,"[Marketing, Python, C, Node, Excel]",2026-06-27T00:00:04+00:00,1782518404,https://remoteok.com/remote-jobs/remote-produc...,NaN,NaN
6,1134171,remote-property-maintenance-amp-operations-coo...,Property Maintenance & Operations Coordinator,Dart,Cayman Islands,NaN,"[Sys Admin, Edu, Non Tech, InfoSec, Technical,...",2026-06-26T20:23:35+00:00,1782505415,https://remoteok.com/remote-jobs/remote-proper...,NaN,NaN
7,1134164,remote-common-energy-office-of-energy-amp-sust...,Common Energy,Office of Energy & Sustainability,Worldwide,NaN,"[Supervisor, Executive, Sys Admin, Customer Su...",2026-06-26T20:20:01+00:00,1782505201,https://remoteok.com/remote-jobs/remote-common...,NaN,NaN
8,1134172,remote-people-operations-specialist-vulncheck-...,People Operations Specialist,VulnCheck,United States,NaN,"[HR, InfoSec, Coordinator, Customer Support, M...",2026-06-26T19:57:38+00:00,1782503858,https://remoteok.com/remote-jobs/remote-people...,NaN,NaN
9,1134158,remote-frontend-developer-junior-universia-per...,Frontend Developer Junior,Universia Perú,Peru,NaN,"[Front End, Developer, Web Developer, JavaScri...",2026-06-26T19:18:48+00:00,1782501528,https://remoteok.com/remote-jobs/remote-fronte...,NaN,NaN
10,1134170,remote-analyst-customer-routing-gildan-1134170,Analyst Customer Routing,Gildan,Worldwide,NaN,"[Sys Admin, Edu, Non Tech, InfoSec, Technical,...",2026-06-26T18:52:19+00:00,1782499939,https://remoteok.com/remote-jobs/remote-analys...,NaN,NaN
11,1134154,remote-customer-support-technician-helpdesk-of...,Customer Support Technician Helpdesk Offboardi...,Pixel Machinery,United States,NaN,"[Customer Support, Design, Jira, SaaS, HR, Sys...",2026-06-26T15:36:59+00:00,1782488219,https://remoteok.com/remote-jobs/remote-custom...,NaN,NaN
12,1134178,remote-user-researcher-ministry-of-housing-com...,User Researcher,"Ministry of Housing, Communities and Local Gov...",Worldwide,NaN,"[Design, Embedded, Sys Admin, InfoSec, Technic...",2026-06-26T15:00:23+00:00,1782486023,https://remoteok.com/remote-jobs/remote-user-r...,NaN,NaN
13,1134162,remote-operator-genuit-group-1134162,Operator,Genuit Group,Worldwide,NaN,"[Supervisor, Executive]",2026-06-26T14:22:04+00:00,1782483724,https://remoteok.com/remote-jobs/remote-operat...,NaN,NaN
14,1134169,remote-aeronautical-information-service-cadet-...,Aeronautical Information Service Cadet,Grenada Airports Authority,Grenada,NaN,"[Sys Admin, Edu, Non Tech, InfoSec, Technical,...",2026-06-26T12:41:21+00:00,1782477681,https://remoteok.com/remote-jobs/remote-aerona...,NaN,NaN
15,1134155,remote-collections-manager-national-service-bu...,Collections Manager,National Service Bureau,United States,NaN,"[Customer Support, Design, Jira, SaaS, HR, Sys...",2026-06-26T11:15:18+00:00,1782472518,https://remoteok.com/remote-jobs/remote-collec...,NaN,NaN
16,1134152,remote-entry-level-administrative-assistant-re...,Entry Level Administrative Assistant,Recruit Lytics Hiring,"المدينة, المدينة المدينة السعودية",NaN,"[Virtual Assistant, Edu, Customer Support, Mar...",2026-06-26T07:51:56+00:00,1782460316,https://remoteok.com/remote-jobs/remote-entry-...,NaN,NaN
17,1134138,remote-administrative-assistant-entry-level-re...,Administrative Assistant Entry Level,Recruit Lytics Hiring,United Kingdom,NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-26T07:51:44+00:00,1782460304,https://remoteok.com/remote-jobs/remote-admini...,NaN,NaN
18,1134179,remote-human-resources-assistant-recruit-lytic...,Human Resources Assistant,Recruit Lytics Hiring,United Kingdom,NaN,"[Design, Embedded, Sys Admin, InfoSec, Technic...",2026-06-26T07:51:21+00:00,1782460281,https://remoteok.com/remote-jobs/remote-human-...,NaN,NaN
19,1134157,remote-file-clerk-recruit-lytics-hiring-1134157,File Clerk,Recruit Lytics Hiring,Hong Kong,NaN,"[Jira, HR, Customer Support, Finance, Cloud, A...",2026-06-26T07:47:42+00:00,1782460062,https://remoteok.com/remote-jobs/remote-file-c...,NaN,NaN
20,1134153,remote-data-entry-specialist-assistant-adminis...,Data Entry Specialist Assistant Administrator,Recruit Lytics Hiring,Hong Kong,NaN,"[Virtual Assistant, Edu, Customer Support, Mar...",2026-06-26T07:47:28+00:00,1782460048,https://remoteok.com/remote-jobs/remote-data-e...,NaN,NaN
21,1134137,remote-virtual-executive-assistant-recruit-lyt...,Virtual Executive Assistant,Recruit Lytics Hiring,"Friesland, Friesland, Nederland",NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-26T07:46:59+00:00,1782460019,https://remoteok.com/remote-jobs/remote-virtua...,NaN,NaN
22,1134156,remote-freelance-designer-awesomehues-1134156,Freelance Designer,Awesomehues,Worldwide,NaN,"[Customer Support, Design, Jira, SaaS, HR, Sys...",2026-06-26T07:37:32+00:00,1782459452,https://remoteok.com/remote-jobs/remote-freela...,NaN,NaN
23,1134151,remote-game-tester-earn-up-500-per-game-jobsin...,Game Tester Earn Up $500 per Game,JobsInMass.com,Worldwide,NaN,"[Executive, Copywriting, Marketing, Speech, Vi...",2026-06-26T07:10:28+00:00,1782457828,https://remoteok.com/remote-jobs/remote-game-t...,NaN,NaN
24,1134150,remote-social-media-manager-ae-onlinejobs-ph-1...,SOCIAL MEDIA MANAGER �,OnlineJobs.PH,Worldwide,NaN,"[Executive, Copywriting, Marketing, Speech, Vi...",2026-06-26T05:55:09+00:00,1782453309,https://remoteok.com/remote-jobs/remote-social...,NaN,NaN
25,1134136,remote-marketing-assistant-onlinejobs-ph-1134136,Marketing Assistant,OnlineJobs.PH,Worldwide,NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-26T05:52:48+00:00,1782453168,https://remoteok.com/remote-jobs/remote-market...,NaN,NaN
26,1134141,remote-i-am-looking-for-guide-mixed-media-labs...,I am looking for guide,"Mixed Media Labs, Inc.",Worldwide,NaN,[],2026-06-26T04:03:45+00:00,1782446625,https://remoteok.com/remote-jobs/remote-i-am-l...,NaN,NaN
27,1134173,remote-claims-specialist-dtla-benefits-1134173,Claims Specialist,DTLA Benefits,United States,NaN,"[HR, InfoSec, Coordinator, Customer Support, M...",2026-06-26T03:00:49+00:00,1782442849,https://remoteok.com/remote-jobs/remote-claims...,NaN,NaN
28,1134149,remote-view-open-positions-minds-worth-meeting...,View Open Positions,Minds Worth Meeting Podcast,Worldwide,NaN,"[Design, Wordpress, Executive, Designer, Ads, ...",2026-06-26T02:13:22+00:00,1782440002,https://remoteok.com/remote-jobs/remote-view-o...,NaN,NaN
29,1134174,remote-genealogista-amorim-global-1134174,Genealogista,Amorim Global,Brazil,NaN,"[Excel, Non Tech]",2026-06-26T00:53:09+00:00,1782435189,https://remoteok.com/remote-jobs/remote-geneal...,NaN,NaN
30,1134128,remote-vice-president-supply-chain-ramp-talent...,Vice President Supply Chain,Ramp Talent,United States,NaN,"[Customer Support, Marketing, Executive, Micro...",2026-06-25T23:57:41+00:00,1782431861,https://remoteok.com/remote-jobs/remote-vice-p...,NaN,NaN
31,1134134,remote-asistente-de-cuentas-marketing-btl-weld...,Asistente de Cuentas Marketing BTL Weldon,Universia Argentina,Argentina,NaN,"[Linguistics, Legal, Non Tech, Marketing]",2026-06-25T23:36:42+00:00,1782430602,https://remoteok.com/remote-jobs/remote-asiste...,NaN,NaN
32,1134130,remote-water-safety-specialist-four-seasons-11...,Water Safety Specialist,Four Seasons,Worldwide,NaN,"[Sys Admin, Edu, Technical, Coordinator, Custo...",2026-06-25T22:54:20+00:00,1782428060,https://remoteok.com/remote-jobs/remote-water-...,NaN,NaN
33,1134139,remote-chief-growth-officer-berni-and-mick-ire...,Chief Growth Officer,Berni and Mick Ireland,United Kingdom,NaN,"[Virtual Assistant, Design, Executive, Coordin...",2026-06-25T22:45:16+00:00,1782427516,https://remoteok.com/remote-jobs/remote-chief-...,NaN,NaN
34,1134163,remote-leakage-inspector-williams-tucker-limit...,Leakage Inspector,Williams Tucker Limited,United Kingdom,NaN,"[Supervisor, Executive]",2026-06-25T20:02:18+00:00,1782417738,https://remoteok.com/remote-jobs/remote-leakag...,NaN,NaN
35,1134140,remote-line-inspector-job-buzzer-1134140,Line inspector,Job Buzzer,Worldwide,NaN,[],2026-06-25T20:01:32+00:00,1782417692,https://remoteok.com/remote-jobs/remote-line-i...,NaN,NaN
36,1134124,remote-clinical-trial-associate-ollin-bioscien...,Clinical Trial Associate,Ollin Biosciences,San Francisco Bay Area,NaN,"[Customer Support, Marketing, Executive, Micro...",2026-06-25T19:29:39+00:00,1782415779,https://remoteok.com/remote-jobs/remote-clinic...,NaN,NaN
37,1134115,remote-product-fashionxyz-1134115,Product,fashionxyz,Worldwide,NaN,[],2026-06-25T17:14:27+00:00,1782407667,https://remoteok.com/remote-jobs/remote-produc...,NaN,NaN
38,1134117,remote-assistant-marketing-manager-little-caes...,Assistant Marketing Manager,Little Caesars Pizza,Worldwide,NaN,"[C, Executive, Virtual Assistant, Sys Admin, S...",2026-06-25T16:37:11+00:00,1782405431,https://remoteok.com/remote-jobs/remote-assist...,NaN,NaN
39,1134108,remote-scheduling-coordinator-entry-level-no-e...,Scheduling Coordinator Entry Level No Experien...,Travel Planning Professionals,United States,NaN,"[Travel, Coordinator, Customer Support, Market...",2026-06-25T14:36:32+00:00,1782398192,https://remoteok.com/remote-jobs/remote-schedu...,NaN,NaN
40,1134127,remote-scheduling-coordinator-entry-level-trav...,Scheduling Coordinator Entry Level,Travel Planning Professionals,United States,NaN,"[Customer Support, Marketing, Executive, Micro...",2026-06-25T14:35:13+00:00,1782398113,https://remoteok.com/remote-jobs/remote-schedu...,NaN,NaN
41,1134109,remote-entry-level-online-scheduling-coordinat...,Entry Level Online Scheduling Coordinator,Travel Planning Professionals,United States,NaN,"[Travel, Coordinator, Customer Support, Market...",2026-06-25T14:29:08+00:00,1782397748,https://remoteok.com/remote-jobs/remote-entry-...,NaN,NaN
42,1134166,remote-school-crossing-patrol-education-author...,School Crossing Patrol,Education Authority (Northern Ireland),Worldwide,NaN,"[Supervisor, Executive, Sys Admin, Customer Su...",2026-06-25T14:24:26+00:00,1782397466,https://remoteok.com/remote-jobs/remote-school...,NaN,NaN
43,1134099,remote-preparador-de-vehiculos-hatillo-enterpr...,Preparador de Vehiculos Hatillo,Enterprise,Puerto Rico,NaN,"[Project Manager, Executive, Sys Admin, InfoSe...",2026-06-25T14:06:28+00:00,1782396388,https://remoteok.com/remote-jobs/remote-prepar...,NaN,NaN
44,1134145,remote-kerendia-task-force-bayer-1134145,Kerendia Task Force,Bayer,Worldwide,NaN,"[Project Manager, Executive, Product Manager, ...",2026-06-25T13:17:49+00:00,1782393469,https://remoteok.com/remote-jobs/remote-kerend...,NaN,NaN
45,1134119,remote-speculative-application-wenzel-designte...,Speculative application,Wenzel DesignTec,Worldwide,NaN,"[Sys Admin, Edu, Technical, Marketing, Finance...",2026-06-25T12:32:54+00:00,1782390774,https://remoteok.com/remote-jobs/remote-specul...,NaN,NaN
46,1134161,remote-team-leader-supervisor-clean-bees-1134161,Team leader supervisor,Clean Bees,United Kingdom,NaN,"[Supervisor, Executive]",2026-06-25T12:31:57+00:00,1782390717,https://remoteok.com/remote-jobs/remote-team-l...,NaN,NaN
47,1134146,remote-hh2-biztech-1134146,hh2,Biztech,Worldwide,NaN,"[Project Manager, Executive, Product Manager, ...",2026-06-25T09:06:30+00:00,1782378390,https://remoteok.com/remote-jobs/remote-hh2-bi...,NaN,NaN
48,1134160,remote-open-position-dauphine-americashare-113...,Open Position — Dauphine,AmericaShare,Worldwide,NaN,[],2026-06-25T07:45:07+00:00,1782373507,https://remoteok.com/remote-jobs/remote-open-p...,NaN,NaN